let page = 1;
let datos = [];
let column = 0;
(function createDivContainer() {
  if (window.innerWidth >= 960) {
    column = 3;
  } else if (window.innerWidth >= 600) {
    column = 2;
  } else {
    column = 1;
  }
  for (let i = 1; i <= column; i++) {
    let divRoot = document.querySelector("#container");
    let div = document.createElement("div");
    divRoot.appendChild(div);
  }
})();
setTimeout(() => {
  getApi(column, 1);
}, 1200);

window.addEventListener("resize", () => {
  document.getElementById("container").innerHTML = "";
  organizarElements(column);
});

window.addEventListener("scroll", function (e) {
  if (
    window.scrollY + window.innerHeight >=
    document.documentElement.scrollHeight - 1500
  ) {
    if (!document.querySelector(".loading")) {
      Loading();
      setTimeout(() => {
        document.querySelector(".loading").remove();
        getApi(column, page);
      }, 1000);
    }
  }
});

function Loading() {
  let container = document.querySelector("main");
  let div = document.createElement("div");
  div.className = "loading";
  div.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: none; display: block; shape-rendering: auto;" width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
  <rect x="15" y="30" width="10" height="40" fill="#1b0629">
    <animate attributeName="opacity" dur="1s" repeatCount="indefinite" calcMode="spline" keyTimes="0;0.5;1" keySplines="0.5 0 0.5 1;0.5 0 0.5 1" values="1;0.2;1" begin="-0.6"/>
  </rect><rect x="35" y="30" width="10" height="40" fill="#dc93f8">
    <animate attributeName="opacity" dur="1s" repeatCount="indefinite" calcMode="spline" keyTimes="0;0.5;1" keySplines="0.5 0 0.5 1;0.5 0 0.5 1" values="1;0.2;1" begin="-0.4"/>
  </rect><rect x="55" y="30" width="10" height="40" fill="#1b0629">
    <animate attributeName="opacity" dur="1s" repeatCount="indefinite" calcMode="spline" keyTimes="0;0.5;1" keySplines="0.5 0 0.5 1;0.5 0 0.5 1" values="1;0.2;1" begin="-0.2"/>
  </rect><rect x="75" y="30" width="10" height="40" fill="#dc93f8">
    <animate attributeName="opacity" dur="1s" repeatCount="indefinite" calcMode="spline" keyTimes="0;0.5;1" keySplines="0.5 0 0.5 1;0.5 0 0.5 1" values="1;0.2;1" begin="-1"/>
  </rect>
  <!-- [ldio] generated by https://loading.io/ --></svg>`;
  container.appendChild(div);
}

async function getApi(column) {
  let count = 1;
  let url = "https://picsum.photos/v2/list?page=" + page + "&limit=10";
  const getData = await fetch(url);
  const images = await getData.json();
  page++;
  for (let i in images) {
    let data = {};
    data.download_url = images[i].download_url;
    data.author = images[i].author;
    let selector = "#container > div:nth-child(" + count + ")";
    let $container = document.querySelector(selector);
    let div = document.createElement("div");
    div.className = "card";
    div.innerHTML = `
    <a target="_blank" href=${images[i].download_url}>
    <img src=${images[i].download_url} loading="lazy" alt=${images[i].author} width="100%">
    <p>Author:  ${images[i].author}</p></a>`;
    datos.push(data);
    $container.appendChild(div);
    count++;
    if (count === column + 1) {
      count = 1;
    }
  }
}

function organizarElements() {
  
  let column = 0;
  if (window.innerWidth >= 960) {
    column = 3;
  } else if (window.innerWidth >= 600) {
    column = 2;
  } else {
    column = 1;
  }
  for (let i = 0; i < column; i++) {
    let divRoot = document.querySelector("#container");
    let div = document.createElement("div");
    divRoot.appendChild(div);
  }
  let count = 1;
  let images = datos;
  for (let i in images) {
    let selector = "#container > div:nth-child(" + count + ")";
    let $container = document.querySelector(selector);
    let div = document.createElement("div");
    div.className = "card";
    div.innerHTML = `
    <a target="_blank" href=${images[i].download_url}>
    <img src=${images[i].download_url} loading="lazy" alt=${images[i].author} width="100%">
    <p>Author:  ${images[i].author}</p></a>`;
    $container.appendChild(div);
    count++;
    if (count === column + 1) {
      count = 1;
    }
  }
}
